
const projects = [
    {
        name: 'Johannesburg Art Gallery Website',
        slug: 'jag',
        category: 'Web Design, UX/UI',
        image: '/images/jag.jpg',
        url: "/jag",
        brand: 'Johannesburg Art Gallery',
        description: 'I created this website design as an upgrade to their current website. ',
    },
    {
        name: 'Thema Agency Website Design',
        slug: 'thema',
        category: 'Web Design, UX/UI',
        image: '/thema-landing.jpg',
        url: "/thema",
        brand: 'Thema Agency',
        description: 'A website design for a made up agency. ',
    },
    {
        name: 'Fundi Foundation Website ',
        slug: 'fundi',
        category: 'Web Design, UX/UI, Development',
        image: '/fundi-landing.png',
        url: "/fundi",
        brand: 'Fundi Foundation',
        description: 'I built and designed this website for the Fundi Foundation. ',
    },
    {
        name: 'Gryphon Lounge website',
        slug: 'gryphon',
        category: 'Web Design, UX/UI, Wordpress',
        image: '/gryphon-landing.jpg',
        url: "/gryphon-lounge",
        brand: 'The Gryphon Lounge',
        description: 'Website for a brand and digital agency in Johannesburg.',
    },
    {
        name: 'Noah Capital Markets',
        slug: 'noah',
        category: 'Web Design, UX/UI, Wordpress',
        image: '/noah-landing.jpg',
        url: "/noah",
        brand: 'Noah Capital Markets',
        description: 'Created a website for Noah Capital Markets. ',
    },
    // {
    //     name: 'Imbeu Website',
    //     slug: 'imbeu',
    //     category: 'Web Design, UX/UI, Wordpress',
    //     image: '/imbeu-landing.jpg',
    //     url: "/imbeu",
    //     brand: 'Imbeu Development and Project Management',
    //     description: 'Created a website for Imbeu Development and Project Management - pty. ',
    // },
    {
        name: 'React Hooks',
        slug: 'react',
        category: 'Coding, ',
        image: '/react-landing.jpg',
        url: "/hooks",
        brand: 'React',
        description: 'List of react hooks and what they do. ',
    },
];
export default projects;